# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_siguienteMainWindow = QtWidgets.QPushButton(self.centralwidget)
        self.btn_siguienteMainWindow.setGeometry(QtCore.QRect(240, 190, 111, 51))
        self.btn_siguienteMainWindow.setObjectName("btn_siguienteMainWindow")
        self.rbtn_moderado = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn_moderado.setGeometry(QtCore.QRect(250, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rbtn_moderado.setFont(font)
        self.rbtn_moderado.setObjectName("rbtn_moderado")
        self.rbtn_poco = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn_poco.setGeometry(QtCore.QRect(250, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rbtn_poco.setFont(font)
        self.rbtn_poco.setObjectName("rbtn_poco")
        self.rbtn_mucho = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn_mucho.setGeometry(QtCore.QRect(250, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rbtn_mucho.setFont(font)
        self.rbtn_mucho.setObjectName("rbtn_mucho")
        self.btn_reiniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reiniciar.setGeometry(QtCore.QRect(20, 250, 91, 31))
        self.btn_reiniciar.setObjectName("btn_reiniciar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SpeedrunGuru - Cuestionario"))
        self.label.setText(_translate("MainWindow", "Pregunta N°1: ¿Cuanto tiempo dispone para jugar?"))
        self.btn_siguienteMainWindow.setText(_translate("MainWindow", "Siguiente pregunta"))
        self.rbtn_moderado.setText(_translate("MainWindow", "Moderado"))
        self.rbtn_poco.setText(_translate("MainWindow", "Poco"))
        self.rbtn_mucho.setText(_translate("MainWindow", "Mucho"))
        self.btn_reiniciar.setText(_translate("MainWindow", "Reiniciar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
